FROM node:16-alpine3.11

LABEL version="1.0"

LABEL description="Development image for the MERN API."

WORKDIR /app

COPY ["package.json", "package-lock.json*.", "npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]